/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/me": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Current user with profile (profile is null until completed) */
        get: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description OK */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["Me"];
                    };
                };
                401: components["responses"]["Error"];
            };
        };
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/me/profile": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        /** Create or replace the profile (FR-003) */
        put: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody: {
                content: {
                    "application/json": components["schemas"]["ProfileInput"];
                };
            };
            responses: {
                /** @description OK */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["Me"];
                    };
                };
                422: components["responses"]["Error"];
            };
        };
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/me/avatar": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        /** Upload avatar photo (JPEG/PNG/WebP, max 2 MB) (FR-004) */
        put: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody: {
                content: {
                    "multipart/form-data": {
                        /** Format: binary */
                        file: string;
                    };
                };
            };
            responses: {
                /** @description OK */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": {
                            avatarUrl?: string;
                        };
                    };
                };
                413: components["responses"]["Error"];
                422: components["responses"]["Error"];
            };
        };
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/me/preferences": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        /** Update theme preference (FR-045) */
        patch: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody: {
                content: {
                    "application/json": {
                        theme: components["schemas"]["Theme"];
                    };
                };
            };
            responses: {
                /** @description Updated */
                204: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content?: never;
                };
            };
        };
        trace?: never;
    };
    "/financial-accounts": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List financial accounts */
        get: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description OK */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": {
                            data?: components["schemas"]["FinancialAccount"][];
                        };
                    };
                };
            };
        };
        put?: never;
        /** Create financial account (FR-007) */
        post: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody: {
                content: {
                    "application/json": components["schemas"]["FinancialAccountInput"];
                };
            };
            responses: {
                /** @description Created */
                201: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["FinancialAccount"];
                    };
                };
                409: components["responses"]["Error"];
                422: components["responses"]["Error"];
            };
        };
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/financial-accounts/{id}": {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: components["parameters"]["Id"];
            };
            cookie?: never;
        };
        /** Get financial account */
        get: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    id: components["parameters"]["Id"];
                };
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description OK */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["FinancialAccount"];
                    };
                };
                404: components["responses"]["Error"];
            };
        };
        /** Update financial account (currency locked once used) */
        put: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    id: components["parameters"]["Id"];
                };
                cookie?: never;
            };
            requestBody: {
                content: {
                    "application/json": components["schemas"]["FinancialAccountInput"];
                };
            };
            responses: {
                /** @description OK */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["FinancialAccount"];
                    };
                };
                409: components["responses"]["Error"];
                422: components["responses"]["Error"];
            };
        };
        post?: never;
        /** Delete financial account; 409 IN_USE if referenced (FR-011) */
        delete: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    id: components["parameters"]["Id"];
                };
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description Deleted */
                204: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content?: never;
                };
                409: components["responses"]["Error"];
            };
        };
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/payors": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List payors */
        get: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description OK */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": {
                            data?: components["schemas"]["Payor"][];
                        };
                    };
                };
            };
        };
        put?: never;
        /** Create payor (FR-009) */
        post: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody: {
                content: {
                    "application/json": components["schemas"]["PayorInput"];
                };
            };
            responses: {
                /** @description Created */
                201: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["Payor"];
                    };
                };
                422: components["responses"]["Error"];
            };
        };
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/payors/{id}": {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: components["parameters"]["Id"];
            };
            cookie?: never;
        };
        /** Get payor */
        get: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    id: components["parameters"]["Id"];
                };
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description OK */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["Payor"];
                    };
                };
            };
        };
        /** Update payor */
        put: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    id: components["parameters"]["Id"];
                };
                cookie?: never;
            };
            requestBody: {
                content: {
                    "application/json": components["schemas"]["PayorInput"];
                };
            };
            responses: {
                /** @description OK */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["Payor"];
                    };
                };
            };
        };
        post?: never;
        /** Delete payor; 409 IN_USE if referenced (FR-011) */
        delete: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    id: components["parameters"]["Id"];
                };
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description Deleted */
                204: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content?: never;
                };
                409: components["responses"]["Error"];
            };
        };
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/vendors": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List vendors */
        get: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description OK */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": {
                            data?: components["schemas"]["Vendor"][];
                        };
                    };
                };
            };
        };
        put?: never;
        /** Create vendor (FR-010) */
        post: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody: {
                content: {
                    "application/json": components["schemas"]["VendorInput"];
                };
            };
            responses: {
                /** @description Created */
                201: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["Vendor"];
                    };
                };
                422: components["responses"]["Error"];
            };
        };
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/vendors/{id}": {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: components["parameters"]["Id"];
            };
            cookie?: never;
        };
        /** Get vendor */
        get: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    id: components["parameters"]["Id"];
                };
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description OK */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["Vendor"];
                    };
                };
            };
        };
        /** Update vendor */
        put: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    id: components["parameters"]["Id"];
                };
                cookie?: never;
            };
            requestBody: {
                content: {
                    "application/json": components["schemas"]["VendorInput"];
                };
            };
            responses: {
                /** @description OK */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["Vendor"];
                    };
                };
            };
        };
        post?: never;
        /** Delete vendor; 409 IN_USE if referenced (FR-011) */
        delete: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    id: components["parameters"]["Id"];
                };
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description Deleted */
                204: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content?: never;
                };
                409: components["responses"]["Error"];
            };
        };
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/budgets": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List budgets with totals to date */
        get: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description OK */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": {
                            data?: components["schemas"]["BudgetSummary"][];
                        };
                    };
                };
            };
        };
        put?: never;
        /**
         * Create a budget (Lite = no categories; Guided/Complete = full tree in one atomic request) (FR-022)
         * @description System "Unplanned" categories/items are always added (FR-033). 409 BUDGET_OVERLAP (FR-014).
         */
        post: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody: {
                content: {
                    "application/json": components["schemas"]["BudgetCreateInput"];
                };
            };
            responses: {
                /** @description Created */
                201: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["BudgetDetail"];
                    };
                };
                409: components["responses"]["Error"];
                422: components["responses"]["Error"];
            };
        };
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/budgets/{id}": {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: components["parameters"]["Id"];
            };
            cookie?: never;
        };
        /** Budget tree with categories, items and per-item totals */
        get: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    id: components["parameters"]["Id"];
                };
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description OK */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["BudgetDetail"];
                    };
                };
                404: components["responses"]["Error"];
            };
        };
        put?: never;
        post?: never;
        /** Delete budget and everything under it (FR-020) */
        delete: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    id: components["parameters"]["Id"];
                };
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description Deleted */
                204: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content?: never;
                };
            };
        };
        options?: never;
        head?: never;
        /** Update name, description, dates, alert threshold (currency immutable) */
        patch: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    id: components["parameters"]["Id"];
                };
                cookie?: never;
            };
            requestBody: {
                content: {
                    "application/json": components["schemas"]["BudgetUpdateInput"];
                };
            };
            responses: {
                /** @description OK */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["BudgetDetail"];
                    };
                };
                /** @description BUDGET_OVERLAP or TRANSACTIONS_OUT_OF_RANGE */
                409: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["Error"];
                    };
                };
            };
        };
        trace?: never;
    };
    "/budgets/{id}/deletion-impact": {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: components["parameters"]["Id"];
            };
            cookie?: never;
        };
        /** Counts shown in the delete confirmation (FR-020) */
        get: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    id: components["parameters"]["Id"];
                };
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description OK */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["DeletionImpact"];
                    };
                };
            };
        };
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/budgets/{id}/categories": {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: components["parameters"]["Id"];
            };
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Create category (FR-015) */
        post: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    id: components["parameters"]["Id"];
                };
                cookie?: never;
            };
            requestBody: {
                content: {
                    "application/json": components["schemas"]["CategoryInput"];
                };
            };
            responses: {
                /** @description Created */
                201: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["Category"];
                    };
                };
                409: components["responses"]["Error"];
                422: components["responses"]["Error"];
            };
        };
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/categories/{id}": {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: components["parameters"]["Id"];
            };
            cookie?: never;
        };
        get?: never;
        put?: never;
        post?: never;
        /** Delete category and its items/transactions; 409 SYSTEM_RECORD for Unplanned */
        delete: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    id: components["parameters"]["Id"];
                };
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description Deleted */
                204: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content?: never;
                };
                409: components["responses"]["Error"];
            };
        };
        options?: never;
        head?: never;
        /** Rename/describe category; 409 SYSTEM_RECORD for Unplanned */
        patch: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    id: components["parameters"]["Id"];
                };
                cookie?: never;
            };
            requestBody: {
                content: {
                    "application/json": {
                        name?: string;
                        description?: string | null;
                    };
                };
            };
            responses: {
                /** @description OK */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["Category"];
                    };
                };
                409: components["responses"]["Error"];
            };
        };
        trace?: never;
    };
    "/categories/{id}/deletion-impact": {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: components["parameters"]["Id"];
            };
            cookie?: never;
        };
        /** Counts shown in the delete confirmation */
        get: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    id: components["parameters"]["Id"];
                };
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description OK */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["DeletionImpact"];
                    };
                };
            };
        };
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/categories/{id}/items": {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: components["parameters"]["Id"];
            };
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Create budget item; buckets generated (FR-016, FR-023) */
        post: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    id: components["parameters"]["Id"];
                };
                cookie?: never;
            };
            requestBody: {
                content: {
                    "application/json": components["schemas"]["BudgetItemInput"];
                };
            };
            responses: {
                /** @description Created */
                201: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["BudgetItem"];
                    };
                };
                422: components["responses"]["Error"];
            };
        };
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/items/{id}": {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: components["parameters"]["Id"];
            };
            cookie?: never;
        };
        /** Item with its buckets */
        get: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    id: components["parameters"]["Id"];
                };
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description OK */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["BudgetItemWithBuckets"];
                    };
                };
            };
        };
        /** Update item; buckets regenerated and transactions re-allocated (409 TRANSACTIONS_OUT_OF_RANGE) */
        put: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    id: components["parameters"]["Id"];
                };
                cookie?: never;
            };
            requestBody: {
                content: {
                    "application/json": components["schemas"]["BudgetItemInput"];
                };
            };
            responses: {
                /** @description OK */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["BudgetItemWithBuckets"];
                    };
                };
                409: components["responses"]["Error"];
                422: components["responses"]["Error"];
            };
        };
        post?: never;
        /** Delete item, buckets and transactions; 409 SYSTEM_RECORD for Unplanned */
        delete: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    id: components["parameters"]["Id"];
                };
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description Deleted */
                204: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content?: never;
                };
                409: components["responses"]["Error"];
            };
        };
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/items/{id}/deletion-impact": {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: components["parameters"]["Id"];
            };
            cookie?: never;
        };
        /** Counts shown in the delete confirmation */
        get: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    id: components["parameters"]["Id"];
                };
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description OK */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["DeletionImpact"];
                    };
                };
            };
        };
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/transactions": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List transactions, newest first (FR-034) */
        get: {
            parameters: {
                query?: {
                    budgetId?: string;
                    itemId?: string;
                    kind?: components["schemas"]["FlowKind"];
                    financialAccountId?: string;
                    payorId?: string;
                    vendorId?: string;
                    from?: string;
                    to?: string;
                    cursor?: string;
                    limit?: number;
                };
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description OK */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": {
                            data?: components["schemas"]["Transaction"][];
                            nextCursor?: string | null;
                        };
                    };
                };
            };
        };
        put?: never;
        /**
         * Record a transaction; allocated to a bucket (FR-026–FR-032)
         * @description 422 CURRENCY_MISMATCH, OUTSIDE_ITEM_RANGE, KIND_MISMATCH. Response includes alerts raised by this write.
         */
        post: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody: {
                content: {
                    "application/json": components["schemas"]["TransactionInput"];
                };
            };
            responses: {
                /** @description Created */
                201: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["TransactionWriteResult"];
                    };
                };
                422: components["responses"]["Error"];
            };
        };
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/transactions/{id}": {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: components["parameters"]["Id"];
            };
            cookie?: never;
        };
        /** Get transaction */
        get: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    id: components["parameters"]["Id"];
                };
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description OK */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["Transaction"];
                    };
                };
            };
        };
        /** Update transaction; buckets and balances recalculated */
        put: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    id: components["parameters"]["Id"];
                };
                cookie?: never;
            };
            requestBody: {
                content: {
                    "application/json": components["schemas"]["TransactionInput"];
                };
            };
            responses: {
                /** @description OK */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["TransactionWriteResult"];
                    };
                };
                422: components["responses"]["Error"];
            };
        };
        post?: never;
        /** Delete transaction; buckets and balances recalculated */
        delete: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    id: components["parameters"]["Id"];
                };
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description Deleted */
                204: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content?: never;
                };
            };
        };
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/dashboard": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Dashboard summary (FR-035); also evaluates ended income buckets (research R9) */
        get: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description OK */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["Dashboard"];
                    };
                };
            };
        };
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/budgets/{id}/reports/forecast-vs-actual": {
        parameters: {
            query: {
                level: "budget" | "category" | "item";
                /** @description category or item id when level != budget */
                targetId?: string;
            };
            header?: never;
            path: {
                id: components["parameters"]["Id"];
            };
            cookie?: never;
        };
        /** Expected vs actual per month (FR-038) */
        get: {
            parameters: {
                query: {
                    level: "budget" | "category" | "item";
                    /** @description category or item id when level != budget */
                    targetId?: string;
                };
                header?: never;
                path: {
                    id: components["parameters"]["Id"];
                };
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description OK */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["ForecastVsActual"];
                    };
                };
            };
        };
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/budgets/{id}/reports/top": {
        parameters: {
            query?: {
                n?: 5 | 10;
                by?: "item" | "counterparty";
                from?: string;
                to?: string;
            };
            header?: never;
            path: {
                id: components["parameters"]["Id"];
            };
            cookie?: never;
        };
        /** Top N incomes and expenses (FR-038) */
        get: {
            parameters: {
                query?: {
                    n?: 5 | 10;
                    by?: "item" | "counterparty";
                    from?: string;
                    to?: string;
                };
                header?: never;
                path: {
                    id: components["parameters"]["Id"];
                };
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description OK */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["TopN"];
                    };
                };
            };
        };
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/budgets/{id}/reports/projection": {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: components["parameters"]["Id"];
            };
            cookie?: never;
        };
        /** Projected end-of-period totals per item and budget, plus unbudgeted totals (FR-039, FR-033a) */
        get: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    id: components["parameters"]["Id"];
                };
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description OK */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["Projection"];
                    };
                };
            };
        };
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/budgets/{id}/reports/insights": {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: components["parameters"]["Id"];
            };
            cookie?: never;
        };
        /** Items consistently deviating from estimate (FR-040) */
        get: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    id: components["parameters"]["Id"];
                };
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description OK */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": {
                            data?: components["schemas"]["Insight"][];
                        };
                    };
                };
            };
        };
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/alerts": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List alerts (excludes dismissed) */
        get: {
            parameters: {
                query?: {
                    unreadOnly?: boolean;
                };
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description OK */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": {
                            data?: components["schemas"]["Alert"][];
                            unreadCount?: number;
                        };
                    };
                };
            };
        };
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/alerts/{id}": {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: components["parameters"]["Id"];
            };
            cookie?: never;
        };
        get?: never;
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        /** Mark read or dismiss (FR-043) */
        patch: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    id: components["parameters"]["Id"];
                };
                cookie?: never;
            };
            requestBody: {
                content: {
                    "application/json": {
                        read?: boolean;
                        dismissed?: boolean;
                    };
                };
            };
            responses: {
                /** @description OK */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["Alert"];
                    };
                };
            };
        };
        trace?: never;
    };
    "/alerts/read-all": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Mark all alerts read */
        post: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description Done */
                204: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content?: never;
                };
            };
        };
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        Error: {
            error: {
                /**
                 * @description UNAUTHENTICATED, PROFILE_INCOMPLETE, NOT_FOUND, VALIDATION_FAILED, IN_USE, SYSTEM_RECORD,
                 *     BUDGET_OVERLAP, TRANSACTIONS_OUT_OF_RANGE, OUTSIDE_ITEM_RANGE, CURRENCY_MISMATCH,
                 *     KIND_MISMATCH, FILE_TOO_LARGE, RATE_LIMITED, INTERNAL_ERROR
                 */
                code: string;
                /** @description Friendly; safe to display */
                message: string;
                /** @description Per-field messages */
                fields?: {
                    [key: string]: string;
                };
                requestId?: string;
            };
        };
        /** @example 5000.00 */
        Money: string;
        /** @enum {string} */
        Currency: "USD" | "COP";
        /** @enum {string} */
        Theme: "SYSTEM" | "LIGHT" | "DARK";
        /** @enum {string} */
        FlowKind: "INCOME" | "EXPENSE";
        /** @enum {string} */
        Frequency: "ONE_TIME" | "DAILY" | "WEEKLY" | "BIWEEKLY" | "MONTHLY" | "QUARTERLY" | "ANNUALLY" | "CUSTOM";
        Timestamps: {
            /** Format: uuid */
            id?: string;
            /** Format: date-time */
            createdAt?: string;
            /** Format: date-time */
            updatedAt?: string;
        };
        ContactFields: {
            address?: string | null;
            city?: string | null;
            postalCode?: string | null;
            state?: string | null;
            /** @description ISO 3166-1 alpha-2 */
            country?: string | null;
            /** @description E.164 */
            phone?: string | null;
        };
        ProfileInput: {
            firstName: string;
            lastName: string;
            username: string;
            address: string;
            city: string;
            postalCode: string;
            state: string;
            country: string;
            phone: string;
            /** @example America/Bogota */
            timeZone: string;
            avatarUrl: string;
        };
        Me: {
            id?: string;
            email?: string;
            username?: string;
            theme?: components["schemas"]["Theme"];
            profile?: components["schemas"]["ProfileInput"] | null;
        };
        FinancialAccountInput: components["schemas"]["ContactFields"] & {
            name: string;
            description?: string | null;
            /** @enum {string} */
            type: "CHECKING" | "SAVINGS" | "CREDIT_CARD" | "CASH" | "DIGITAL_WALLET" | "BROKERAGE" | "LOAN" | "OTHER";
            currency: components["schemas"]["Currency"];
            openingBalance: components["schemas"]["Money"];
        };
        FinancialAccount: components["schemas"]["Timestamps"] & components["schemas"]["FinancialAccountInput"] & {
            currentBalance?: components["schemas"]["Money"];
            inUse?: boolean;
        };
        PayorInput: components["schemas"]["ContactFields"] & {
            name: string;
            description?: string | null;
            /** @enum {string} */
            type: "EMPLOYER" | "INVESTMENTS" | "RENTAL" | "BUSINESS_CLIENT" | "GOVERNMENT_BENEFITS" | "OTHER";
            currency: components["schemas"]["Currency"];
        };
        Payor: components["schemas"]["Timestamps"] & components["schemas"]["PayorInput"] & {
            inUse?: boolean;
        };
        VendorInput: components["schemas"]["ContactFields"] & {
            name: string;
            description?: string | null;
            /** @enum {string} */
            type: "UTILITY" | "SUBSCRIPTION" | "RETAIL" | "GROCERIES" | "RESTAURANT" | "HOUSING" | "HEALTHCARE" | "INSURANCE" | "TRANSPORTATION" | "GOVERNMENT_TAXES" | "OTHER";
            currency: components["schemas"]["Currency"];
        };
        Vendor: components["schemas"]["Timestamps"] & components["schemas"]["VendorInput"] & {
            inUse?: boolean;
        };
        BudgetItemInput: {
            name: string;
            description: string;
            /**
             * Format: date
             * @description Defaults to budget start
             */
            startDate?: string;
            /**
             * Format: date
             * @description Defaults to budget end; clipped if beyond
             */
            endDate?: string;
            estimatedAmount: components["schemas"]["Money"];
            /** Format: date */
            estimatedExecutionDate: string;
            frequency: components["schemas"]["Frequency"];
            customInterval?: number | null;
            /** @enum {string|null} */
            customUnit?: "DAYS" | "MONTHS" | null;
        };
        BudgetItem: components["schemas"]["Timestamps"] & components["schemas"]["BudgetItemInput"] & {
            /** Format: uuid */
            categoryId?: string;
            kind?: components["schemas"]["FlowKind"];
            currency?: components["schemas"]["Currency"];
            isSystem?: boolean;
            expectedToDate?: components["schemas"]["Money"];
            actualToDate?: components["schemas"]["Money"];
            adjustments?: "END_DATE_CLIPPED"[];
            /** @description Bucket open today or the next one (budget detail only) */
            currentBucket?: components["schemas"]["Bucket"] | null;
        };
        Bucket: {
            /** Format: uuid */
            id?: string;
            sequence?: number;
            /** Format: date */
            startDate?: string;
            /** Format: date */
            endDate?: string;
            /** Format: date */
            estimatedExecutionDate?: string;
            estimatedAmount?: components["schemas"]["Money"];
            actualAmount?: components["schemas"]["Money"];
            /** Format: date */
            actualDate?: string | null;
            currency?: components["schemas"]["Currency"];
            /** @enum {string} */
            status?: "PAST" | "CURRENT" | "FUTURE";
            over?: boolean;
        };
        BudgetItemWithBuckets: components["schemas"]["BudgetItem"] & {
            /** Format: uuid */
            budgetId?: string;
            categoryName?: string;
            buckets?: components["schemas"]["Bucket"][];
        };
        CategoryInput: {
            kind: components["schemas"]["FlowKind"];
            name: string;
            description?: string | null;
        };
        Category: components["schemas"]["Timestamps"] & components["schemas"]["CategoryInput"] & {
            /** Format: uuid */
            budgetId?: string;
            isSystem?: boolean;
            items?: components["schemas"]["BudgetItem"][];
        };
        BudgetCreateInput: {
            name: string;
            description?: string | null;
            currency: components["schemas"]["Currency"];
            /** Format: date */
            startDate: string;
            /** Format: date */
            endDate: string;
            /** @default 10 */
            alertThresholdPct: number;
            /**
             * @default LITE
             * @enum {string}
             */
            mode: "LITE" | "GUIDED" | "COMPLETE";
            /** @description Guided/Complete only. Saved atomically with the budget. */
            categories?: (components["schemas"]["CategoryInput"] & {
                items?: components["schemas"]["BudgetItemInput"][];
            })[];
        };
        BudgetUpdateInput: {
            name?: string;
            description?: string | null;
            /** Format: date */
            startDate?: string;
            /** Format: date */
            endDate?: string;
            alertThresholdPct?: number;
        };
        BudgetSummary: components["schemas"]["Timestamps"] & {
            name?: string;
            description?: string | null;
            currency?: components["schemas"]["Currency"];
            /** Format: date */
            startDate?: string;
            /** Format: date */
            endDate?: string;
            alertThresholdPct?: number;
            /** @description today within dates */
            isActive?: boolean;
            totals?: components["schemas"]["Totals"];
        };
        BudgetDetail: components["schemas"]["BudgetSummary"] & {
            categories?: components["schemas"]["Category"][];
        };
        Totals: {
            expectedIncomeToDate?: components["schemas"]["Money"];
            actualIncomeToDate?: components["schemas"]["Money"];
            expectedExpenseToDate?: components["schemas"]["Money"];
            actualExpenseToDate?: components["schemas"]["Money"];
            unbudgetedIncome?: components["schemas"]["Money"];
            unbudgetedExpense?: components["schemas"]["Money"];
        };
        DeletionImpact: {
            categories?: number;
            items?: number;
            buckets?: number;
            transactions?: number;
        };
        TransactionInput: {
            kind: components["schemas"]["FlowKind"];
            amount: components["schemas"]["Money"];
            currency: components["schemas"]["Currency"];
            /**
             * Format: date-time
             * @description Local date-time with offset
             */
            occurredAt: string;
            /** @description IANA zone. Create: defaults to the profile zone. Update: omitted = keep the stored zone (FR-031) */
            timeZone?: string;
            /** Format: uuid */
            itemId: string;
            /** Format: uuid */
            financialAccountId: string;
            /**
             * Format: uuid
             * @description Required for INCOME
             */
            payorId?: string | null;
            /**
             * Format: uuid
             * @description Required for EXPENSE
             */
            vendorId?: string | null;
            note?: string | null;
        };
        Transaction: components["schemas"]["Timestamps"] & components["schemas"]["TransactionInput"] & {
            timeZone?: string;
            /** Format: date */
            localDate?: string;
            /** Format: uuid */
            bucketId?: string;
            /** Format: uuid */
            budgetId?: string;
            itemName?: string;
            origin?: {
                id?: string;
                name?: string;
                /** @enum {string} */
                type?: "PAYOR" | "FINANCIAL_ACCOUNT";
            };
            destination?: {
                id?: string;
                name?: string;
                /** @enum {string} */
                type?: "VENDOR" | "FINANCIAL_ACCOUNT";
            };
        };
        TransactionWriteResult: {
            transaction?: components["schemas"]["Transaction"];
            bucket?: components["schemas"]["Bucket"];
            newAlerts?: components["schemas"]["Alert"][];
        };
        Alert: {
            /** Format: uuid */
            id?: string;
            /** @enum {string} */
            type?: "ITEM_EXPENSE_OVER" | "ITEM_INCOME_UNDER" | "BUDGET_EXPENSE_OVER" | "BUDGET_INCOME_UNDER";
            /** Format: uuid */
            budgetId?: string;
            budgetName?: string;
            /** Format: uuid */
            itemId?: string | null;
            itemName?: string | null;
            /** Format: uuid */
            bucketId?: string | null;
            expectedAmount?: components["schemas"]["Money"];
            actualAmount?: components["schemas"]["Money"];
            currency?: components["schemas"]["Currency"];
            thresholdPct?: number;
            /** @description Friendly text ready to display */
            message?: string;
            read?: boolean;
            cleared?: boolean;
            /** Format: date-time */
            createdAt?: string;
        };
        Dashboard: {
            activeBudgets?: components["schemas"]["BudgetSummary"][];
            recentTransactions?: components["schemas"]["Transaction"][];
            financialAccounts?: components["schemas"]["FinancialAccount"][];
            unreadAlerts?: components["schemas"]["Alert"][];
            unreadAlertCount?: number;
        };
        ForecastVsActual: {
            currency?: components["schemas"]["Currency"];
            series?: {
                /** @description YYYY-MM */
                period?: string;
                kind?: components["schemas"]["FlowKind"];
                expected?: components["schemas"]["Money"];
                actual?: components["schemas"]["Money"];
            }[];
        };
        TopN: {
            currency?: components["schemas"]["Currency"];
            incomes?: components["schemas"]["RankedAmount"][];
            expenses?: components["schemas"]["RankedAmount"][];
        };
        RankedAmount: {
            id?: string;
            name?: string;
            amount?: components["schemas"]["Money"];
            sharePct?: number;
        };
        Projection: {
            currency?: components["schemas"]["Currency"];
            income?: components["schemas"]["ProjectionTotals"];
            expense?: components["schemas"]["ProjectionTotals"];
            items?: (components["schemas"]["ProjectionTotals"] & {
                /** Format: uuid */
                itemId?: string;
                name?: string;
                kind?: components["schemas"]["FlowKind"];
                isSystem?: boolean;
                ratio?: number;
            })[];
        };
        ProjectionTotals: {
            planned?: components["schemas"]["Money"];
            actualToDate?: components["schemas"]["Money"];
            projected?: components["schemas"]["Money"];
            unbudgeted?: components["schemas"]["Money"];
        };
        Insight: {
            /** Format: uuid */
            itemId?: string;
            itemName?: string;
            kind?: components["schemas"]["FlowKind"];
            deviatingBuckets?: number;
            completedBuckets?: number;
            averageDeviationPct?: number;
            /** @description e.g. "Netflix was over its estimate in 3 of 4 months. Consider raising the estimate to $22.00 or reviewing the subscription." */
            suggestion?: string;
        };
    };
    responses: {
        /** @description Error with a user-friendly message */
        Error: {
            headers: {
                [name: string]: unknown;
            };
            content: {
                "application/json": components["schemas"]["Error"];
            };
        };
    };
    parameters: {
        Id: string;
    };
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export type operations = Record<string, never>;
