/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AppRouteImport } from './routes/_app'
import { Route as LoginRouteImport } from './routes/login'
import { Route as SignupRouteImport } from './routes/signup'
import { Route as AppDashboardRouteImport } from './routes/_app/dashboard'
import { Route as AppProfileRouteImport } from './routes/_app/profile'
import { Route as OnboardingProfileRouteImport } from './routes/onboarding.profile'
import { Route as AppAccountsIndexRouteImport } from './routes/_app/accounts/index'
import { Route as AppAccountsIdRouteImport } from './routes/_app/accounts/$id'
import { Route as AppAccountsNewRouteImport } from './routes/_app/accounts/new'
import { Route as AppBudgetsIndexRouteImport } from './routes/_app/budgets/index'
import { Route as AppPayorsIndexRouteImport } from './routes/_app/payors/index'
import { Route as AppPayorsIdRouteImport } from './routes/_app/payors/$id'
import { Route as AppPayorsNewRouteImport } from './routes/_app/payors/new'
import { Route as AppReportsIndexRouteImport } from './routes/_app/reports/index'
import { Route as AppTransactionsIndexRouteImport } from './routes/_app/transactions/index'
import { Route as AppTransactionsIdRouteImport } from './routes/_app/transactions/$id'
import { Route as AppTransactionsNewRouteImport } from './routes/_app/transactions/new'
import { Route as AppVendorsIndexRouteImport } from './routes/_app/vendors/index'
import { Route as AppVendorsIdRouteImport } from './routes/_app/vendors/$id'
import { Route as AppVendorsNewRouteImport } from './routes/_app/vendors/new'
import { Route as AppBudgetsBudgetIdIndexRouteImport } from './routes/_app/budgets/$budgetId/index'
import { Route as AppBudgetsBudgetIdReportsRouteImport } from './routes/_app/budgets/$budgetId/reports'
import { Route as AppBudgetsNewLiteRouteImport } from './routes/_app/budgets/new.lite'
import { Route as AppBudgetsBudgetIdItemsItemIdRouteImport } from './routes/_app/budgets/$budgetId/items/$itemId'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AppRoute = AppRouteImport.update({
  id: '/_app',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const SignupRoute = SignupRouteImport.update({
  id: '/signup',
  path: '/signup',
  getParentRoute: () => rootRouteImport,
} as any)
const AppDashboardRoute = AppDashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => AppRoute,
} as any)
const AppProfileRoute = AppProfileRouteImport.update({
  id: '/profile',
  path: '/profile',
  getParentRoute: () => AppRoute,
} as any)
const OnboardingProfileRoute = OnboardingProfileRouteImport.update({
  id: '/onboarding/profile',
  path: '/onboarding/profile',
  getParentRoute: () => rootRouteImport,
} as any)
const AppAccountsIndexRoute = AppAccountsIndexRouteImport.update({
  id: '/accounts/',
  path: '/accounts/',
  getParentRoute: () => AppRoute,
} as any)
const AppAccountsIdRoute = AppAccountsIdRouteImport.update({
  id: '/accounts/$id',
  path: '/accounts/$id',
  getParentRoute: () => AppRoute,
} as any)
const AppAccountsNewRoute = AppAccountsNewRouteImport.update({
  id: '/accounts/new',
  path: '/accounts/new',
  getParentRoute: () => AppRoute,
} as any)
const AppBudgetsIndexRoute = AppBudgetsIndexRouteImport.update({
  id: '/budgets/',
  path: '/budgets/',
  getParentRoute: () => AppRoute,
} as any)
const AppPayorsIndexRoute = AppPayorsIndexRouteImport.update({
  id: '/payors/',
  path: '/payors/',
  getParentRoute: () => AppRoute,
} as any)
const AppPayorsIdRoute = AppPayorsIdRouteImport.update({
  id: '/payors/$id',
  path: '/payors/$id',
  getParentRoute: () => AppRoute,
} as any)
const AppPayorsNewRoute = AppPayorsNewRouteImport.update({
  id: '/payors/new',
  path: '/payors/new',
  getParentRoute: () => AppRoute,
} as any)
const AppReportsIndexRoute = AppReportsIndexRouteImport.update({
  id: '/reports/',
  path: '/reports/',
  getParentRoute: () => AppRoute,
} as any)
const AppTransactionsIndexRoute = AppTransactionsIndexRouteImport.update({
  id: '/transactions/',
  path: '/transactions/',
  getParentRoute: () => AppRoute,
} as any)
const AppTransactionsIdRoute = AppTransactionsIdRouteImport.update({
  id: '/transactions/$id',
  path: '/transactions/$id',
  getParentRoute: () => AppRoute,
} as any)
const AppTransactionsNewRoute = AppTransactionsNewRouteImport.update({
  id: '/transactions/new',
  path: '/transactions/new',
  getParentRoute: () => AppRoute,
} as any)
const AppVendorsIndexRoute = AppVendorsIndexRouteImport.update({
  id: '/vendors/',
  path: '/vendors/',
  getParentRoute: () => AppRoute,
} as any)
const AppVendorsIdRoute = AppVendorsIdRouteImport.update({
  id: '/vendors/$id',
  path: '/vendors/$id',
  getParentRoute: () => AppRoute,
} as any)
const AppVendorsNewRoute = AppVendorsNewRouteImport.update({
  id: '/vendors/new',
  path: '/vendors/new',
  getParentRoute: () => AppRoute,
} as any)
const AppBudgetsBudgetIdIndexRoute = AppBudgetsBudgetIdIndexRouteImport.update({
  id: '/budgets/$budgetId/',
  path: '/budgets/$budgetId/',
  getParentRoute: () => AppRoute,
} as any)
const AppBudgetsBudgetIdReportsRoute =
  AppBudgetsBudgetIdReportsRouteImport.update({
    id: '/budgets/$budgetId/reports',
    path: '/budgets/$budgetId/reports',
    getParentRoute: () => AppRoute,
  } as any)
const AppBudgetsNewLiteRoute = AppBudgetsNewLiteRouteImport.update({
  id: '/budgets/new/lite',
  path: '/budgets/new/lite',
  getParentRoute: () => AppRoute,
} as any)
const AppBudgetsBudgetIdItemsItemIdRoute =
  AppBudgetsBudgetIdItemsItemIdRouteImport.update({
    id: '/budgets/$budgetId/items/$itemId',
    path: '/budgets/$budgetId/items/$itemId',
    getParentRoute: () => AppRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/login': typeof LoginRoute
  '/signup': typeof SignupRoute
  '/dashboard': typeof AppDashboardRoute
  '/profile': typeof AppProfileRoute
  '/onboarding/profile': typeof OnboardingProfileRoute
  '/accounts/$id': typeof AppAccountsIdRoute
  '/accounts/new': typeof AppAccountsNewRoute
  '/payors/$id': typeof AppPayorsIdRoute
  '/payors/new': typeof AppPayorsNewRoute
  '/transactions/$id': typeof AppTransactionsIdRoute
  '/transactions/new': typeof AppTransactionsNewRoute
  '/vendors/$id': typeof AppVendorsIdRoute
  '/vendors/new': typeof AppVendorsNewRoute
  '/accounts/': typeof AppAccountsIndexRoute
  '/budgets/': typeof AppBudgetsIndexRoute
  '/payors/': typeof AppPayorsIndexRoute
  '/reports/': typeof AppReportsIndexRoute
  '/transactions/': typeof AppTransactionsIndexRoute
  '/vendors/': typeof AppVendorsIndexRoute
  '/budgets/$budgetId/reports': typeof AppBudgetsBudgetIdReportsRoute
  '/budgets/new/lite': typeof AppBudgetsNewLiteRoute
  '/budgets/$budgetId/': typeof AppBudgetsBudgetIdIndexRoute
  '/budgets/$budgetId/items/$itemId': typeof AppBudgetsBudgetIdItemsItemIdRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/login': typeof LoginRoute
  '/signup': typeof SignupRoute
  '/dashboard': typeof AppDashboardRoute
  '/profile': typeof AppProfileRoute
  '/onboarding/profile': typeof OnboardingProfileRoute
  '/accounts/$id': typeof AppAccountsIdRoute
  '/accounts/new': typeof AppAccountsNewRoute
  '/payors/$id': typeof AppPayorsIdRoute
  '/payors/new': typeof AppPayorsNewRoute
  '/transactions/$id': typeof AppTransactionsIdRoute
  '/transactions/new': typeof AppTransactionsNewRoute
  '/vendors/$id': typeof AppVendorsIdRoute
  '/vendors/new': typeof AppVendorsNewRoute
  '/accounts': typeof AppAccountsIndexRoute
  '/budgets': typeof AppBudgetsIndexRoute
  '/payors': typeof AppPayorsIndexRoute
  '/reports': typeof AppReportsIndexRoute
  '/transactions': typeof AppTransactionsIndexRoute
  '/vendors': typeof AppVendorsIndexRoute
  '/budgets/$budgetId/reports': typeof AppBudgetsBudgetIdReportsRoute
  '/budgets/new/lite': typeof AppBudgetsNewLiteRoute
  '/budgets/$budgetId': typeof AppBudgetsBudgetIdIndexRoute
  '/budgets/$budgetId/items/$itemId': typeof AppBudgetsBudgetIdItemsItemIdRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_app': typeof AppRouteWithChildren
  '/login': typeof LoginRoute
  '/signup': typeof SignupRoute
  '/_app/dashboard': typeof AppDashboardRoute
  '/_app/profile': typeof AppProfileRoute
  '/onboarding/profile': typeof OnboardingProfileRoute
  '/_app/accounts/$id': typeof AppAccountsIdRoute
  '/_app/accounts/new': typeof AppAccountsNewRoute
  '/_app/payors/$id': typeof AppPayorsIdRoute
  '/_app/payors/new': typeof AppPayorsNewRoute
  '/_app/transactions/$id': typeof AppTransactionsIdRoute
  '/_app/transactions/new': typeof AppTransactionsNewRoute
  '/_app/vendors/$id': typeof AppVendorsIdRoute
  '/_app/vendors/new': typeof AppVendorsNewRoute
  '/_app/accounts/': typeof AppAccountsIndexRoute
  '/_app/budgets/': typeof AppBudgetsIndexRoute
  '/_app/payors/': typeof AppPayorsIndexRoute
  '/_app/reports/': typeof AppReportsIndexRoute
  '/_app/transactions/': typeof AppTransactionsIndexRoute
  '/_app/vendors/': typeof AppVendorsIndexRoute
  '/_app/budgets/$budgetId/reports': typeof AppBudgetsBudgetIdReportsRoute
  '/_app/budgets/new/lite': typeof AppBudgetsNewLiteRoute
  '/_app/budgets/$budgetId/': typeof AppBudgetsBudgetIdIndexRoute
  '/_app/budgets/$budgetId/items/$itemId': typeof AppBudgetsBudgetIdItemsItemIdRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/login'
    | '/signup'
    | '/dashboard'
    | '/profile'
    | '/onboarding/profile'
    | '/accounts/$id'
    | '/accounts/new'
    | '/payors/$id'
    | '/payors/new'
    | '/transactions/$id'
    | '/transactions/new'
    | '/vendors/$id'
    | '/vendors/new'
    | '/accounts/'
    | '/budgets/'
    | '/payors/'
    | '/reports/'
    | '/transactions/'
    | '/vendors/'
    | '/budgets/$budgetId/reports'
    | '/budgets/new/lite'
    | '/budgets/$budgetId/'
    | '/budgets/$budgetId/items/$itemId'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/login'
    | '/signup'
    | '/dashboard'
    | '/profile'
    | '/onboarding/profile'
    | '/accounts/$id'
    | '/accounts/new'
    | '/payors/$id'
    | '/payors/new'
    | '/transactions/$id'
    | '/transactions/new'
    | '/vendors/$id'
    | '/vendors/new'
    | '/accounts'
    | '/budgets'
    | '/payors'
    | '/reports'
    | '/transactions'
    | '/vendors'
    | '/budgets/$budgetId/reports'
    | '/budgets/new/lite'
    | '/budgets/$budgetId'
    | '/budgets/$budgetId/items/$itemId'
  id:
    | '__root__'
    | '/'
    | '/_app'
    | '/login'
    | '/signup'
    | '/_app/dashboard'
    | '/_app/profile'
    | '/onboarding/profile'
    | '/_app/accounts/$id'
    | '/_app/accounts/new'
    | '/_app/payors/$id'
    | '/_app/payors/new'
    | '/_app/transactions/$id'
    | '/_app/transactions/new'
    | '/_app/vendors/$id'
    | '/_app/vendors/new'
    | '/_app/accounts/'
    | '/_app/budgets/'
    | '/_app/payors/'
    | '/_app/reports/'
    | '/_app/transactions/'
    | '/_app/vendors/'
    | '/_app/budgets/$budgetId/reports'
    | '/_app/budgets/new/lite'
    | '/_app/budgets/$budgetId/'
    | '/_app/budgets/$budgetId/items/$itemId'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AppRoute: typeof AppRouteWithChildren
  LoginRoute: typeof LoginRoute
  SignupRoute: typeof SignupRoute
  OnboardingProfileRoute: typeof OnboardingProfileRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_app': {
      id: '/_app'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AppRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/signup': {
      id: '/signup'
      path: '/signup'
      fullPath: '/signup'
      preLoaderRoute: typeof SignupRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_app/dashboard': {
      id: '/_app/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof AppDashboardRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/profile': {
      id: '/_app/profile'
      path: '/profile'
      fullPath: '/profile'
      preLoaderRoute: typeof AppProfileRouteImport
      parentRoute: typeof AppRoute
    }
    '/onboarding/profile': {
      id: '/onboarding/profile'
      path: '/onboarding/profile'
      fullPath: '/onboarding/profile'
      preLoaderRoute: typeof OnboardingProfileRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_app/accounts/': {
      id: '/_app/accounts/'
      path: '/accounts'
      fullPath: '/accounts/'
      preLoaderRoute: typeof AppAccountsIndexRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/accounts/$id': {
      id: '/_app/accounts/$id'
      path: '/accounts/$id'
      fullPath: '/accounts/$id'
      preLoaderRoute: typeof AppAccountsIdRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/accounts/new': {
      id: '/_app/accounts/new'
      path: '/accounts/new'
      fullPath: '/accounts/new'
      preLoaderRoute: typeof AppAccountsNewRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/budgets/': {
      id: '/_app/budgets/'
      path: '/budgets'
      fullPath: '/budgets/'
      preLoaderRoute: typeof AppBudgetsIndexRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/payors/': {
      id: '/_app/payors/'
      path: '/payors'
      fullPath: '/payors/'
      preLoaderRoute: typeof AppPayorsIndexRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/payors/$id': {
      id: '/_app/payors/$id'
      path: '/payors/$id'
      fullPath: '/payors/$id'
      preLoaderRoute: typeof AppPayorsIdRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/payors/new': {
      id: '/_app/payors/new'
      path: '/payors/new'
      fullPath: '/payors/new'
      preLoaderRoute: typeof AppPayorsNewRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/reports/': {
      id: '/_app/reports/'
      path: '/reports'
      fullPath: '/reports/'
      preLoaderRoute: typeof AppReportsIndexRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/transactions/': {
      id: '/_app/transactions/'
      path: '/transactions'
      fullPath: '/transactions/'
      preLoaderRoute: typeof AppTransactionsIndexRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/transactions/$id': {
      id: '/_app/transactions/$id'
      path: '/transactions/$id'
      fullPath: '/transactions/$id'
      preLoaderRoute: typeof AppTransactionsIdRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/transactions/new': {
      id: '/_app/transactions/new'
      path: '/transactions/new'
      fullPath: '/transactions/new'
      preLoaderRoute: typeof AppTransactionsNewRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/vendors/': {
      id: '/_app/vendors/'
      path: '/vendors'
      fullPath: '/vendors/'
      preLoaderRoute: typeof AppVendorsIndexRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/vendors/$id': {
      id: '/_app/vendors/$id'
      path: '/vendors/$id'
      fullPath: '/vendors/$id'
      preLoaderRoute: typeof AppVendorsIdRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/vendors/new': {
      id: '/_app/vendors/new'
      path: '/vendors/new'
      fullPath: '/vendors/new'
      preLoaderRoute: typeof AppVendorsNewRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/budgets/$budgetId/': {
      id: '/_app/budgets/$budgetId/'
      path: '/budgets/$budgetId'
      fullPath: '/budgets/$budgetId/'
      preLoaderRoute: typeof AppBudgetsBudgetIdIndexRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/budgets/$budgetId/reports': {
      id: '/_app/budgets/$budgetId/reports'
      path: '/budgets/$budgetId/reports'
      fullPath: '/budgets/$budgetId/reports'
      preLoaderRoute: typeof AppBudgetsBudgetIdReportsRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/budgets/new/lite': {
      id: '/_app/budgets/new/lite'
      path: '/budgets/new/lite'
      fullPath: '/budgets/new/lite'
      preLoaderRoute: typeof AppBudgetsNewLiteRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/budgets/$budgetId/items/$itemId': {
      id: '/_app/budgets/$budgetId/items/$itemId'
      path: '/budgets/$budgetId/items/$itemId'
      fullPath: '/budgets/$budgetId/items/$itemId'
      preLoaderRoute: typeof AppBudgetsBudgetIdItemsItemIdRouteImport
      parentRoute: typeof AppRoute
    }
  }
}

interface AppRouteChildren {
  AppDashboardRoute: typeof AppDashboardRoute
  AppProfileRoute: typeof AppProfileRoute
  AppAccountsIdRoute: typeof AppAccountsIdRoute
  AppAccountsNewRoute: typeof AppAccountsNewRoute
  AppPayorsIdRoute: typeof AppPayorsIdRoute
  AppPayorsNewRoute: typeof AppPayorsNewRoute
  AppTransactionsIdRoute: typeof AppTransactionsIdRoute
  AppTransactionsNewRoute: typeof AppTransactionsNewRoute
  AppVendorsIdRoute: typeof AppVendorsIdRoute
  AppVendorsNewRoute: typeof AppVendorsNewRoute
  AppAccountsIndexRoute: typeof AppAccountsIndexRoute
  AppBudgetsIndexRoute: typeof AppBudgetsIndexRoute
  AppPayorsIndexRoute: typeof AppPayorsIndexRoute
  AppReportsIndexRoute: typeof AppReportsIndexRoute
  AppTransactionsIndexRoute: typeof AppTransactionsIndexRoute
  AppVendorsIndexRoute: typeof AppVendorsIndexRoute
  AppBudgetsBudgetIdReportsRoute: typeof AppBudgetsBudgetIdReportsRoute
  AppBudgetsNewLiteRoute: typeof AppBudgetsNewLiteRoute
  AppBudgetsBudgetIdIndexRoute: typeof AppBudgetsBudgetIdIndexRoute
  AppBudgetsBudgetIdItemsItemIdRoute: typeof AppBudgetsBudgetIdItemsItemIdRoute
}

const AppRouteChildren: AppRouteChildren = {
  AppDashboardRoute: AppDashboardRoute,
  AppProfileRoute: AppProfileRoute,
  AppAccountsIdRoute: AppAccountsIdRoute,
  AppAccountsNewRoute: AppAccountsNewRoute,
  AppPayorsIdRoute: AppPayorsIdRoute,
  AppPayorsNewRoute: AppPayorsNewRoute,
  AppTransactionsIdRoute: AppTransactionsIdRoute,
  AppTransactionsNewRoute: AppTransactionsNewRoute,
  AppVendorsIdRoute: AppVendorsIdRoute,
  AppVendorsNewRoute: AppVendorsNewRoute,
  AppAccountsIndexRoute: AppAccountsIndexRoute,
  AppBudgetsIndexRoute: AppBudgetsIndexRoute,
  AppPayorsIndexRoute: AppPayorsIndexRoute,
  AppReportsIndexRoute: AppReportsIndexRoute,
  AppTransactionsIndexRoute: AppTransactionsIndexRoute,
  AppVendorsIndexRoute: AppVendorsIndexRoute,
  AppBudgetsBudgetIdReportsRoute: AppBudgetsBudgetIdReportsRoute,
  AppBudgetsNewLiteRoute: AppBudgetsNewLiteRoute,
  AppBudgetsBudgetIdIndexRoute: AppBudgetsBudgetIdIndexRoute,
  AppBudgetsBudgetIdItemsItemIdRoute: AppBudgetsBudgetIdItemsItemIdRoute,
}

const AppRouteWithChildren = AppRoute._addFileChildren(AppRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AppRoute: AppRouteWithChildren,
  LoginRoute: LoginRoute,
  SignupRoute: SignupRoute,
  OnboardingProfileRoute: OnboardingProfileRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
